services:
  db:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d/
      - ./backups:/backups/
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "5432:5432"
    restart: always

  app:
    depends_on:
      - db
    build:
      context: ./app
    env_file:
      - .env
    environment:
      PGHOST: db
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    restart: always

volumes:
  pgdata:
